### ISSUE TITLE
新建django2+工程时，根据示例步骤执行python manage.py gen_all出现编码错误

### ISSUE THREAD

**Issue by AngelLiang** [mtianyan/tyadmin_api_cli#2]
## 环境

- Windows 10
- Python36
- PowerShell
- django 2.2

## 报错

按README步骤自建django工程，执行`python manage.py gen_all`这一步报编码错误。

```
> python manage.py gen_all
...
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "F:\github\Django-Demos\DJ28-tyadmin_api_cli-demo\.venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "F:\github\Django-Demos\DJ28-tyadmin_api_cli-demo\.venv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "F:\github\Django-Demos\DJ28-tyadmin_api_cli-demo\.venv\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "F:\github\Django-Demos\DJ28-tyadmin_api_cli-demo\.venv\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "F:\github\Django-Demos\DJ28-tyadmin_api_cli-demo\.venv\lib\site-packages\tyadmin_api_cli\management\commands\gen_all.py", line 38, in handle
    gen_all(setting_value, apps_list)
  File "F:\github\Django-Demos\DJ28-tyadmin_api_cli-demo\.venv\lib\site-packages\tyadmin_api_cli\init_filter_serial_url_view.py", line 18, in gen_all        
    gen_antd_pages(project_name_settings, models_list)
  File "F:\github\Django-Demos\DJ28-tyadmin_api_cli-demo\.venv\lib\site-packages\tyadmin_api_cli\deal_antd_pages.py", line 773, in gen_antd_pages
    content = fr.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8d in position 574: illegal multibyte sequence
```

## 相关配置

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'tyadmin_api_cli',
    'order',
]

...

TY_ADMIN_CONFIG = {
    'GEN_APPS': [
        'auth',
        'order',  # 自定义app
    ]
}
```

**Comment by AngelLiang** [comment]
找打原因了，几个文件代码中的`open('..index.jsx')`改为`open('..index.jsx', encoding='utf-8')`即可

**Comment by mtianyan** [comment]
已merge
