### ISSUE TITLE
操作失败了，

### ISSUE THREAD

**Issue by sqw637** [mtianyan/tyadmin_api_cli#6]
python manage.py init_admin && python manage.py gen_all

C:\Users\Administrator\Envs\tyadmin\lib\site-packages\tyadmin_api_cli
******************** 已自动生成urls ********************
C:\Users\Administrator\Envs\tyadmin\lib\site-packages\tyadmin_api_cli
{'auth': ['Permission', 'Group'], 'contenttypes': ['ContentType']}
******************** 已自动生成views ********************
C:\Users\Administrator\Envs\tyadmin\lib\site-packages\tyadmin_api_cli
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
auth Group Permission
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
{'Permission': ['content_type$分割$ContentType'], 'Group': [], 'ContentType': []}
{'Permission': [], 'Group': ['permissions$分割$Permission'], 'ContentType': []}
{'Permission': ['content_type$分割$ContentType'], 'Group': [], 'ContentType': []}
******************** 已自动生成serializers ********************
C:\Users\Administrator\Envs\tyadmin\lib\site-packages\tyadmin_api_cli
******************** 已自动生成filters ********************
C:\Users\Administrator\Envs\tyadmin\lib\site-packages\tyadmin_api_cli
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
auth
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
id
name
content_type
content_type
auth.Permission.content_type
codename
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Administrator\Envs\tyadmin\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Administrator\Envs\tyadmin\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Administrator\Envs\tyadmin\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Administrator\Envs\tyadmin\lib\site-packages\django\core\management\base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Administrator\Envs\tyadmin\lib\site-packages\tyadmin_api_cli\management\commands\gen_all.py", line 38, in handle
    gen_all(setting_value, apps_list)
  File "C:\Users\Administrator\Envs\tyadmin\lib\site-packages\tyadmin_api_cli\init_filter_serial_url_view.py", line 18, in gen_all
    gen_antd_pages(project_name_settings, models_list)
  File "C:\Users\Administrator\Envs\tyadmin\lib\site-packages\tyadmin_api_cli\deal_antd_pages.py", line 912, in gen_antd_pages
    os.mkdir(cur_path)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\Administrator\\Desktop\\TyadminDemo/tyadmin/src/pages/AutoGenPage/PermissionList'

**Comment by mtianyan** [comment]
os.mkdir  改为 os.makedirs 试一下

**Comment by ramwin** [comment]
我也遇到了一样的问题. 然后我手工创建了 src/pages/AutoGenPage
然后gen_all操作成功, 但是npm run start 失败. 报错如下
```
These dependencies were not found:
* @/pages/AutoGenPage/InstructionRecordList/service in ./src/pages/AutoGenPage/ChangeHistoryList/index.jsx, ./src/pages/AutoGenPage/HistoricalIPOProductInfoList/index.jsx and 4 others
```
看上去好像是对外键的自动生成有问题.

**Comment by ramwin** [comment]
很不错的项目,

**Comment by mtianyan** [comment]
@ramwin 加群分享一下model问题情况 我好复现下呢。 交流反馈群: 304094780

**Comment by mtianyan** [comment]
@ramwin 你这个问题看起来是你安装了包含model的第三方app，但你没把这个app加入gen_app。你可以试下0.7新版呢
